apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: fincalc-pro
  namespace: fincalc
  labels:
    app: fincalc-pro
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: fincalc-pro
