apiVersion: v1
kind: Service
metadata:
  name: fincalc-pro
  namespace: fincalc
  labels:
    app: fincalc-pro
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: fincalc-pro
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fincalc-pro
  namespace: fincalc
  labels:
    app: fincalc-pro
